<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1ea1857e5930afd2b5cf2fb38f3a2216
{
    public static $prefixesPsr0 = array (
        'c' => 
        array (
            'cogpowered\\FineDiff' => 
            array (
                0 => __DIR__ . '/..' . '/cogpowered/finediff/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit1ea1857e5930afd2b5cf2fb38f3a2216::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
